name: aqueduct_coverage_tool
description: Collects coverage for Aqueduct
version: 0.0.1

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  crypto: ^2.0.0
  coverage:
    git:
      url: https://github.com/joeconwaystk/coverage.git
      ref: master

dev_dependencies:
  test: ^0.12.0

executables:
  main: main

